name: Hourly Create Round Task

on:
  schedule:
    - cron: "7,17,27,37,47,57 * * * *"
  workflow_dispatch:

jobs:
  create-round:
    runs-on: ubuntu-latest
    steps:
      - name: Call Create Round API
        run: |
          curl -X POST "${{ secrets.API_URL }}/game_rounds"
