name: Hourly Settle Rounds Task

on:
  schedule:
    cron: "7,17,27,37,47,57 * * * *"
  workflow_dispatch:

jobs:
  settle:
    runs-on: ubuntu-latest
    steps:
      - name: Call Settle API
        run: |
          curl -X POST "${{ secrets.API_URL }}/game_rounds/settle"
