name: Price API Test

on:
  workflow_dispatch:

jobs:
  test_api:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch BTC Price from CryptoWatch
        run: |
          # BinanceのBTC/USDT価格をCryptoWatch経由で取得
          curl -s "https://api.cryptowat.ch/markets/binance/btcusdt/price"